In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
Transformed_Housing_Data = pd.read_csv('/content/drive/MyDrive/Notebooks/Module 4 data exploration /3. categorical variable Data Exploration/Transformed_Housing_Data')

In [33]:
Transformed_Housing_Data = Transformed_Housing_Data.rename(columns= {'Sale Price' : 'Sale_Price'})
Transformed_Housing_Data = Transformed_Housing_Data.rename(columns= {'Waterfront View' : 'Waterfront_View'})
Transformed_Housing_Data = Transformed_Housing_Data.rename(columns= {'Condition of the House' : 'Condition_of_the_House'})
Transformed_Housing_Data = Transformed_Housing_Data.rename(columns= {'Ever Renovated' : 'Ever_Renovated'})

In [34]:
Transformed_Housing_Data = pd.get_dummies(Transformed_Housing_Data,columns=['Condition_of_the_House','Ever_Renovated','Waterfront_View'] , drop_first=True)

In [35]:
Transformed_Housing_Data.head()

           ID  Sale_Price  ...  Ever_Renovated_Yes  Waterfront_View_Yes
0  7129300520    221900.0  ...                   0                    0
1  6414100192    538000.0  ...                   1                    0
2  5631500400    180000.0  ...                   0                    0
3  2487200875    604000.0  ...                   0                    0
4  1954400510    510000.0  ...                   0                    0

[5 rows x 24 columns]

# BINNING

In [36]:
Zip_Table = Transformed_Housing_Data.groupby('Zipcode').agg({'Sale_Price':'mean'}).sort_values('Sale_Price',ascending = True)

In [37]:
Zip_Table

           Sale_Price
Zipcode
98002.0  2.342840e+05
98168.0  2.403284e+05
98032.0  2.512962e+05
98001.0  2.808047e+05
98148.0  2.849086e+05
...               ...
98109.0  7.876028e+05
98112.0  8.807990e+05
98040.0  9.621087e+05
98004.0  9.869679e+05
98039.0  1.102126e+06

[70 rows x 1 columns]

In [38]:
Zip_Table['Zipcode_Group'] = pd.cut(Zip_Table['Sale_Price'] , bins = 10 ,
                                    labels = ['Zipcode_Group  _0',
                                              'Zipcode_Group  _1',
                                              'Zipcode_Group  _2',
                                              'Zipcode_Group  _3',
                                              'Zipcode_Group  _4',
                                              'Zipcode_Group  _5',
                                              'Zipcode_Group  _6',
                                              'Zipcode_Group  _7',
                                              'Zipcode_Group  _8',
                                              'Zipcode_Group  _9'],
                                    include_lowest = True)

In [39]:
Zip_Table = Zip_Table.drop(columns = 'Sale_Price')

In [41]:
Transformed_Housing_Data = pd.merge(Transformed_Housing_Data,
                                    Zip_Table,
                                    left_on = 'Zipcode',
                                    how = 'left',
                                    right_index = True)

In [42]:
Transformed_Housing_Data = Transformed_Housing_Data.drop(columns='Zipcode')

In [43]:
Transformed_Housing_Data.head()

           ID  Sale_Price  ...  Waterfront_View_Yes      Zipcode_Group
0  7129300520    221900.0  ...                    0  Zipcode_Group  _0
1  6414100192    538000.0  ...                    0  Zipcode_Group  _2
2  5631500400    180000.0  ...                    0  Zipcode_Group  _2
3  2487200875    604000.0  ...                    0  Zipcode_Group  _3
4  1954400510    510000.0  ...                    0  Zipcode_Group  _4

[5 rows x 24 columns]

In [44]:
Transformed_Housing_Data = pd.get_dummies(Transformed_Housing_Data,columns=['Zipcode_Group'] , drop_first=True)

In [45]:
Transformed_Housing_Data.head()

           ID  ...  Zipcode_Group_Zipcode_Group  _9
0  7129300520  ...                                0
1  6414100192  ...                                0
2  5631500400  ...                                0
3  2487200875  ...                                0
4  1954400510  ...                                0

[5 rows x 32 columns]

In [46]:
# Data set is named Transformed _housing _ dada _ 2